config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homepage#index"

  resources :user_roles, only: [:index]

  resources :topics, only: [:show] do
    resources :spelling_tasks, only: [:new]
    resources :categories, only: [:show, :edit, :update] do
      resources :exercises, only: [:show, :create]
    end
  end

  # API
  namespace :api, defaults: {format: 'json'} do
    resources :topics, only: [:create, :index, :destroy]
    resources :user_roles, only: [:update]
    resources :category_spelling_tasks, only: [:show]
    resources :spelling_tasks, only: [:create, :destroy]
    resources :topic_categories, only: [:show]
    resources :categories, only: [:create, :update, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is?('admin')
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  serialize :response_options, Array

  belongs_to :topic
  has_many :spelling_tasks

  validates :title, :short_title, :response_options, :amount, presence: true
  validates :amount, inclusion: 1..100
  validates :title, :short_title, uniqueness: {message: 'Kategorie bereits vorhanden'}
end

app/models/spelling_task.rb
class SpellingTask < ActiveRecord::Base
  belongs_to :category

  validates :solution_text, :fill_in_text, :category_id, presence: true
  validates :solution_text, uniqueness: { scope: :category_id, message: 'Dieses Wort gibt es in der Kategorie bereits.' }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %w[admin therapist teacher]
  serialize :roles, Array 

  def is?(role)
    roles.include?(role)
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    respond_to :json
  end
end

app/controllers/api/categories_controller.rb
module Api
  class CategoriesController < ApiController
    load_and_authorize_resource only: [:create, :destroy, :update]

    def create
      @category = Category.create(category_params)
    end

    def update
      @category.update_attributes(category_params)
    end

    def destroy
      @category.destroy
    end

    private

    def category_params
      params.require(:category).permit(:topic_id, :id, :short_title, :title, :description, :amount, :url, response_options: [])
    end
  end
end

app/controllers/api/category_spelling_tasks_controller.rb
module Api
  class CategorySpellingTasksController < ApiController
    load_and_authorize_resource :category, parent: false

    def show
      @spelling_tasks = @category.spelling_tasks.order('lower(solution_text)')
    end
  end
end

app/controllers/api/spelling_tasks_controller.rb
module Api
  class SpellingTasksController < ApiController
    load_and_authorize_resource only: [:create, :destroy]

    def create
      @spelling_task = SpellingTask.create(spelling_task_params)
    end

    def destroy
      @spelling_task.destroy
    end

    private

    def spelling_task_params
      params.require(:spelling_task).permit(:solution_text, :fill_in_text, :category_id)
    end
  end
end

app/controllers/api/topic_categories_controller.rb
module Api
  class TopicCategoriesController < ApiController
    load_and_authorize_resource :topic, parent: false

    def show
      @categories = @topic.categories.order('lower(short_title)')
    end
  end
end

app/controllers/api/topics_controller.rb
module Api
  class TopicsController < ApiController
    load_and_authorize_resource only: [:create, :index, :destroy]

    def create
      @topic = Topic.create(topic_params)
    end

    def index
    end

    def destroy
      @topic.destroy
    end

    private

    def topic_params
      params.require(:topic).permit(:title, :description)
    end
  end
end

app/controllers/api/user_roles_controller.rb
module Api
  class UserRolesController < ApiController
    load_and_authorize_resource :user, parent: false

    def update
      @user.update_attributes(update_params)
    end

    private

    def update_params
      params.require(:user).permit(roles: [])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :remember_me])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :username, :email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource :topic
  load_and_authorize_resource

  before_action :serialize_response_options, only: [:update]

  def edit; end

  def update
    if @category.update_attributes(category_params)
      flash[:notice] = "Änderungen wurden übernommen."
    else
      flash[:alert] = "Fehler. Bitte Eingaben überprüfen."
    end
    render :edit, flash: flash
  end

  def show
    session[:task_ids] = nil
    session[:current_task_index] = nil
  end

  private

  def category_params
    params
      .require(:category)
      .permit(:title, :short_title, :description, :amount, response_options: [])
      .merge(response_options: serialize_response_options)
  end

  def serialize_response_options
    Hash[*params[:category][:response_options]].map do |key, value|
      next if key.empty?
      {"name" => key, "value" => value}
    end.compact
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_filter :category

  def create
    @task_ids = @category.spelling_tasks.map(&:id).shuffle.take(@category.amount)
    session[:task_ids] = @task_ids

    load_spelling_task
    
    render :show
  end

  def show
    @task_ids = session[:task_ids]
    load_spelling_task

    @progress = (100 * (@next_task_index - 1)) / @category.amount
    
    if @next_task_index == @task_ids.length
      @next_task_index = nil
    end

  end

  private

  def category
    @category = Category.find(params[:category_id]) 
  end

  def load_spelling_task
    index = params[:id].present? ? params[:id].to_i : 0
    @spelling_task = SpellingTask.find(@task_ids[index])
    @next_task_index = index + 1
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  load_resource :topic, parent: false

  def index
  end
end

app/controllers/spelling_tasks_controller.rb
class SpellingTasksController < ApplicationController
  load_and_authorize_resource :topic, id_param: :topic_id
  
  def new
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource

  def show
  end
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  load_and_authorize_resource :user, parent: false

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/categories/_response_option.html.haml
= option_fields.label :name
%input{name: "category[response_options][]", value: local_assigns[:name]}

= option_fields.label :value
%input{name: "category[response_options][]", value: local_assigns[:value]}

app/views/categories/edit.html.haml
= form_for(@category, url: topic_category_path(@topic, @category)) do |form|
  = form.label :title
  = form.text_field :title

  = form.label :short_title
  = form.text_field :short_title

  = form.label :description
  = form.text_area :description

  = form.label :amount
  = form.text_field :amount

  %hr
  = form.fields_for :response_options do |option_fields|
    - @category.response_options.each do |response_option|
      = render "response_option", option_fields: option_fields, name: response_option[:name], value: response_option[:value]
      %hr

    - (2 - @category.response_options.size).times do
      = render "response_option", option_fields: option_fields
      %hr
    = render "response_option", option_fields: option_fields
    %hr

  = form.submit "Speichern"

%a{href: "#{topic_path(@topic)}"} Zurück zur Übersicht

app/views/categories/show.html.haml
.jumbotron
  %h1= @category.title
  %p= @category.description
  = button_to('Start', topic_category_exercises_path(@category.topic, @category), method: :post, class: 'js--reset-session-storage btn btn-lg btn-primary')

app/views/exercises/index.html.erb
<h1><%= @category.description %></h1>
<% if @spelling_task.present? %>
	<div><%= @spelling_task.fill_in_text %></div>
	<% @category.response_options.each do |response_option| %>
		<%= button_to(response_option, '#') %>
	<% end %>
<% end %>

<%= @task_ids.inspect %>
<%= session[:current_task_index] %>

app/views/exercises/show.html.haml
- if @spelling_task.present?
  .exercise.js--task
    .progress
      .progress-bar.progress-bar-success.js--progress{style: "width: #{@progress}%"}
        = "#{@progress || 0}%"
    %h1
      .js--fill-in-text= @spelling_task.fill_in_text
      .js--solution-text{style: "display:none"}= @spelling_task.solution_text
    - @category.response_options.each do |response_option|
      - name = response_option[:name]
      - value = response_option[:value]
      - correct = @spelling_task.fill_in_text.gsub('__', value).downcase == @spelling_task.solution_text.downcase
      %button.btn.btn-lg.btn-task.js--check{class: "is-#{correct}", data: {container: 'body', toggle: 'popover', placement: 'bottom', content: (correct ? 'Richtig :)' : 'Fast ;)')}}= name
    .exercise--buttons
      - if @next_task_index.present?
        %a.btn.btn-lg.btn-default.has-full-width.js--next{style: 'display:none', href:topic_category_exercise_path(@category.topic, @category, @next_task_index)} Weiter
      - else
        %a.btn.btn-lg.btn-default.has-full-width.js--next.is-complete{style: 'display:none', href: topic_path(@category.topic)} Zurück zur Übersicht
        %p
          %br
          %br
        .js--score{style: "display:none"}
          %h4.js--success-score
          %h4.js--failure-score

app/views/homepage/index.html.haml
.jumbotron
  %h1 Lega...was?
  %p Schön, dass du hier bist. <br>Damit hast du den wichtigsten Schritt schon geschafft: den Anfang. <br>Was möchtest du heute üben?
  - @topics.each do |topic|
    %a.btn.btn-primary.btn-lg{href: topic_path(topic)}= topic.title

- if current_user.is?('admin')
  %table.table.js--topic

app/views/spelling_tasks/new.html.haml
%form.form-horizontal
  %fieldset
    
    %legend Aufgaben bearbeiten
    .js--category
      .form-group
        %label.col-md-4.control-label{:for => "category"} Kategorie
        .col-md-4
          %select#Kategorie.form-control.js--select{:name => "category"}
            %option{value: ''} Bitte wählen...
            - @topic.categories.each do |category|
              %option{:value => category.id}= category.short_title

      %table.table.js--spelling-tasks

app/views/topics/show.html.haml
.jumbotron
  %h1= @topic.title
  %p= @topic.description

  - @topic.categories.each do |category|
    %a.btn.btn-lg.btn-primary.has-margin{href: topic_category_path(@topic, category)}
      = category.short_title

  - if current_user.is?('admin')
    .admin--button
      %a.btn.btn-warning.btn-lg{href: new_topic_spelling_task_path(@topic)}
        Aufgaben bearbeiten

- if current_user.is?('admin')
  %table.table.js--categories{data: {id: @topic.id}}

app/views/user_roles/index.html.haml
.table-responsive
  %table.table.table-striped.table-condensed
    %tr
      %th Username
      %th E-Mail
      %th Rolle
      %th Erstellt am
    - @users.each do |user|
      %tr.js--user-role{data: {id: user.id}}
        %td= user.username
        %td= user.email
        %td
          - User::ROLES.each do |role|
            .checkbox.js--check
              %label
                %input.js--role{type: 'checkbox', value: role, checked: user.is?(role) ? 'checked' : nil, disabled: current_user == user && role == 'admin'}= role.capitalize 
        %td= user.created_at