config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homepage#index"

  resources :user_roles, only: [:index]

  resources :topics, only: [:show] do
    resources :spelling_tasks, only: [:new]
    resources :categories, only: [:show, :edit, :update] do
      resources :exercises, only: [:show, :create]
    end
  end

  # API
  namespace :api, defaults: {format: 'json'} do
    resources :topics, only: [:create, :index, :destroy]
    resources :user_roles, only: [:update]
    resources :category_spelling_tasks, only: [:show]
    resources :spelling_tasks, only: [:create, :destroy]
    resources :topic_categories, only: [:show]
    resources :categories, only: [:create, :update, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.is?('admin')
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  serialize :response_options, Array

  belongs_to :topic
  has_many :spelling_tasks

  validates :title, :short_title, :response_options, :amount, presence: true
  validates :amount, inclusion: 1..100
  validates :title, :short_title, uniqueness: {message: 'Kategorie bereits vorhanden'}
end

app/models/spelling_task.rb
class SpellingTask < ActiveRecord::Base
  belongs_to :category

  validates :solution_text, :fill_in_text, :category_id, presence: true
  validates :solution_text, uniqueness: { scope: :category_id, message: 'Dieses Wort gibt es in der Kategorie bereits.' }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %w[admin therapist teacher]
  serialize :roles, Array 

  def is?(role)
    roles.include?(role)
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    respond_to :json
  end
end

app/controllers/api/categories_controller.rb
module Api
  class CategoriesController < ApiController
    load_and_authorize_resource only: [:create, :destroy, :update]

    def create
      @category = Category.create(category_params)
    end

    def update
      @category.update_attributes(category_params)
    end

    def destroy
      @category.destroy
    end

    private

    def category_params
      params.require(:category).permit(:topic_id, :id, :short_title, :title, :description, :amount, :url, response_options: [])
    end
  end
end

app/controllers/api/spelling_tasks_controller.rb
module Api
  class SpellingTasksController < ApiController
    load_and_authorize_resource only: [:create, :destroy]

    def create
      @spelling_task = SpellingTask.create(spelling_task_params)
    end

    def destroy
      @spelling_task.destroy
    end

    private

    def spelling_task_params
      params.require(:spelling_task).permit(:solution_text, :fill_in_text, :category_id)
    end
  end
end

app/controllers/api/topic_categories_controller.rb
module Api
  class TopicCategoriesController < ApiController
    load_and_authorize_resource :topic, parent: false

    def show
      @categories = @topic.categories.order('lower(short_title)')
    end
  end
end

app/controllers/api/topics_controller.rb
module Api
  class TopicsController < ApiController
    load_and_authorize_resource only: [:create, :index, :destroy]

    def create
      @topic = Topic.create(topic_params)
    end

    def index
    end

    def destroy
      @topic.destroy
    end

    private

    def topic_params
      params.require(:topic).permit(:title, :description)
    end
  end
end

app/controllers/api/user_roles_controller.rb
module Api
  class UserRolesController < ApiController
    load_and_authorize_resource :user, parent: false

    def update
      @user.update_attributes(update_params)
    end

    private

    def update_params
      params.require(:user).permit(roles: [])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation, :remember_me])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :username, :email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource :topic
  load_and_authorize_resource

  before_action :serialize_response_options, only: [:update]

  def edit; end

  def update
    if @category.update_attributes(category_params)
      flash[:notice] = "Änderungen wurden übernommen."
    else
      flash[:alert] = "Fehler. Bitte Eingaben überprüfen."
    end
    render :edit, flash: flash
  end

  def show
    session[:task_ids] = nil
    session[:current_task_index] = nil
  end

  private

  def category_params
    params
      .require(:category)
      .permit(:title, :short_title, :description, :amount, response_options: [])
      .merge(response_options: serialize_response_options)
  end

  def serialize_response_options
    Hash[*params[:category][:response_options]].map do |key, value|
      next if key.empty?
      {"name" => key, "value" => value}
    end.compact
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_filter :category

  def create
    @task_ids = @category.spelling_tasks.map(&:id).shuffle.take(@category.amount)
    session[:task_ids] = @task_ids

    load_spelling_task
    
    render :show
  end

  def show
    @task_ids = session[:task_ids]
    load_spelling_task

    @progress = (100 * (@next_task_index - 1)) / @category.amount
    
    if @next_task_index == @task_ids.length
      @next_task_index = nil
    end

  end

  private

  def category
    @category = Category.find(params[:category_id]) 
  end

  def load_spelling_task
    index = params[:id].present? ? params[:id].to_i : 0
    @spelling_task = SpellingTask.find(@task_ids[index])
    @next_task_index = index + 1
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  load_resource :topic, parent: false

  def index
  end
end

app/controllers/spelling_tasks_controller.rb
class SpellingTasksController < ApplicationController
  load_and_authorize_resource :topic, id_param: :topic_id
  
  def new
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource

  def show
  end
end

app/controllers/user_roles_controller.rb
class UserRolesController < ApplicationController
  load_and_authorize_resource :user, parent: false

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/layouts/_navigation.html.haml
- @topics ||= Topic.all
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{aria: {expanded: 'false'}, data: {target: "#bs-example-navbar-collapse-1", toggle: "collapse"}, type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} Lega...was

    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - @topics.each do |topic|
          %li.dropdown
            %a.dropdown-toggle{aria: {expanded: 'false', haspopup: 'true'}, data: {toggle: 'dropdown'}, href: '#', role: 'button'}
              = topic.title
              %span.caret
            %ul.dropdown-menu
              - topic.categories.each do |category|
                %li= link_to(category.short_title, topic_category_path(topic, category))
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{aria: {expanded: 'false', haspopup: 'true'}, data: {toggle: 'dropdown'}, href: '#', role: 'button'}
            - if user_signed_in?
              Hallo
              %strong= current_user.username
              %ul.dropdown-menu
                %li= link_to 'Profil bearbeiten', edit_user_registration_path, class: 'navbar-link'
                %li= link_to 'Rollen bearbeiten', user_roles_path, class: 'navbar-link' if current_user.is?('admin')
                %li= link_to "Abmelden", destroy_user_session_path, method: :delete, class: 'navbar-link'
            - else
              Anmelden
              %ul.dropdown-menu
                %li= link_to 'Account erstellen', new_user_registration_path, class: 'navbar-link'
                %li= link_to 'Einloggen', new_user_session_path, class: 'navbar-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Lega...was
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .application--header
      = render 'layouts/navigation'
    .container.application--content
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      = yield
    .application--footer